export const ADD_MENU_ITEM_REQUEST = 'ADD_MENU_ITEM_REQUEST';
export const ADD_MENU_ITEM_SUCCESS = 'ADD_MENU_ITEM_SUCCESS';
export const ADD_MENU_ITEM_FAIL = 'ADD_MENU_ITEM_FAIL';

export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAIL = 'FETCH_MENU_FAIL';

export const UPDATE_MENU_ITEM_REQUEST = 'UPDATE_MENU_ITEM_REQUEST';
export const UPDATE_MENU_ITEM_SUCCESS = 'UPDATE_MENU_ITEM_SUCCESS';
export const UPDATE_MENU_ITEM_FAIL = 'UPDATE_MENU_ITEM_FAIL';

export const DELETE_MENU_ITEM_REQUEST = 'DELETE_MENU_ITEM_REQUEST';
export const DELETE_MENU_ITEM_SUCCESS = 'DELETE_MENU_ITEM_SUCCESS';
export const DELETE_MENU_ITEM_FAIL = 'DELETE_MENU_ITEM_FAIL';
